#dataSource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: YRQ
    password: 456789
    url: jdbc:mysql://localhost:3306/epidemic?useUnicode=true&characterEncoding=utf8

  #thymeleaf cache close
  thymeleaf:
    cache: false


#pojo package typealiases
mybatis:
  type-aliases-package: com.zywl.pojo




